data:
  sdc:
    users:
      - username: user1
        password: password1
        role: USER_ONE
      - username: user2
        password: password2
        role: USER_TWO

server:
## example to setup SSL
#  ssl:
#    key-store: config/finmath.p12
#    key-store-password: password
#    key-store-type: pkcs12
#  port: 8443
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
    tryItOutEnabled: true

#springdoc:
#  api-docs:
#    enabled: true
#    path: '/v3/api-docs'
#  swagger-ui:
#    server: 'https://valuation-xva-blockchain.com'
spring:
  thymeleaf:
    prefix: 'src/main/resources/templates/' # Prefix that gets prepended to view names when building a URL.
