//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A type describing each of the constituents of a basket.
 * 
 * <p>Java class for BasketConstituent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasketConstituent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/confirmation}PayerReceiver.model" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.fpml.org/FpML-5/confirmation}underlyingAsset"/&gt;
 *         &lt;element name="constituentWeight" type="{http://www.fpml.org/FpML-5/confirmation}ConstituentWeight" minOccurs="0"/&gt;
 *         &lt;element name="dividendPayout" type="{http://www.fpml.org/FpML-5/confirmation}DividendPayout" minOccurs="0"/&gt;
 *         &lt;element name="underlyerPrice" type="{http://www.fpml.org/FpML-5/confirmation}Price" minOccurs="0"/&gt;
 *         &lt;element name="underlyerNotional" type="{http://www.fpml.org/FpML-5/confirmation}Money" minOccurs="0"/&gt;
 *         &lt;element name="underlyerSpread" type="{http://www.fpml.org/FpML-5/confirmation}SpreadScheduleReference" minOccurs="0"/&gt;
 *         &lt;element name="couponPayment" type="{http://www.fpml.org/FpML-5/confirmation}PendingPayment" minOccurs="0"/&gt;
 *         &lt;element name="underlyerFinancing" type="{http://www.fpml.org/FpML-5/confirmation}UnderlyerInterestLeg" minOccurs="0"/&gt;
 *         &lt;element name="underlyerLoanRate" type="{http://www.fpml.org/FpML-5/confirmation}UnderlyerLoanRate" minOccurs="0"/&gt;
 *         &lt;element name="underlyerCollateral" type="{http://www.fpml.org/FpML-5/confirmation}Collateral" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasketConstituent", propOrder = {
    "payerPartyReference",
    "payerAccountReference",
    "receiverPartyReference",
    "receiverAccountReference",
    "underlyingAsset",
    "constituentWeight",
    "dividendPayout",
    "underlyerPrice",
    "underlyerNotional",
    "underlyerSpread",
    "couponPayment",
    "underlyerFinancing",
    "underlyerLoanRate",
    "underlyerCollateral"
})
public class BasketConstituent {

    protected PartyReference payerPartyReference;
    protected AccountReference payerAccountReference;
    protected PartyReference receiverPartyReference;
    protected AccountReference receiverAccountReference;
    @XmlElementRef(name = "underlyingAsset", namespace = "http://www.fpml.org/FpML-5/confirmation", type = JAXBElement.class)
    protected JAXBElement<? extends Asset> underlyingAsset;
    protected ConstituentWeight constituentWeight;
    protected DividendPayout dividendPayout;
    protected Price underlyerPrice;
    protected Money underlyerNotional;
    protected SpreadScheduleReference underlyerSpread;
    protected PendingPayment couponPayment;
    protected UnderlyerInterestLeg underlyerFinancing;
    protected UnderlyerLoanRate underlyerLoanRate;
    protected Collateral underlyerCollateral;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the payerPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getPayerPartyReference() {
        return payerPartyReference;
    }

    /**
     * Sets the value of the payerPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setPayerPartyReference(PartyReference value) {
        this.payerPartyReference = value;
    }

    /**
     * Gets the value of the payerAccountReference property.
     * 
     * @return
     *     possible object is
     *     {@link AccountReference }
     *     
     */
    public AccountReference getPayerAccountReference() {
        return payerAccountReference;
    }

    /**
     * Sets the value of the payerAccountReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountReference }
     *     
     */
    public void setPayerAccountReference(AccountReference value) {
        this.payerAccountReference = value;
    }

    /**
     * Gets the value of the receiverPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getReceiverPartyReference() {
        return receiverPartyReference;
    }

    /**
     * Sets the value of the receiverPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setReceiverPartyReference(PartyReference value) {
        this.receiverPartyReference = value;
    }

    /**
     * Gets the value of the receiverAccountReference property.
     * 
     * @return
     *     possible object is
     *     {@link AccountReference }
     *     
     */
    public AccountReference getReceiverAccountReference() {
        return receiverAccountReference;
    }

    /**
     * Sets the value of the receiverAccountReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountReference }
     *     
     */
    public void setReceiverAccountReference(AccountReference value) {
        this.receiverAccountReference = value;
    }

    /**
     * Gets the value of the underlyingAsset property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Index }{@code >}
     *     {@link JAXBElement }{@code <}{@link EquityAsset }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExchangeTradedFund }{@code >}
     *     {@link JAXBElement }{@code <}{@link MutualFund }{@code >}
     *     {@link JAXBElement }{@code <}{@link Mortgage }{@code >}
     *     {@link JAXBElement }{@code <}{@link Commodity }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cash }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvertibleBond }{@code >}
     *     {@link JAXBElement }{@code <}{@link Future }{@code >}
     *     {@link JAXBElement }{@code <}{@link Bond }{@code >}
     *     {@link JAXBElement }{@code <}{@link Loan }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExchangeTradedOption }{@code >}
     *     {@link JAXBElement }{@code <}{@link Basket }{@code >}
     *     {@link JAXBElement }{@code <}{@link Asset }{@code >}
     *     
     */
    public JAXBElement<? extends Asset> getUnderlyingAsset() {
        return underlyingAsset;
    }

    /**
     * Sets the value of the underlyingAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Index }{@code >}
     *     {@link JAXBElement }{@code <}{@link EquityAsset }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExchangeTradedFund }{@code >}
     *     {@link JAXBElement }{@code <}{@link MutualFund }{@code >}
     *     {@link JAXBElement }{@code <}{@link Mortgage }{@code >}
     *     {@link JAXBElement }{@code <}{@link Commodity }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cash }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvertibleBond }{@code >}
     *     {@link JAXBElement }{@code <}{@link Future }{@code >}
     *     {@link JAXBElement }{@code <}{@link Bond }{@code >}
     *     {@link JAXBElement }{@code <}{@link Loan }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExchangeTradedOption }{@code >}
     *     {@link JAXBElement }{@code <}{@link Basket }{@code >}
     *     {@link JAXBElement }{@code <}{@link Asset }{@code >}
     *     
     */
    public void setUnderlyingAsset(JAXBElement<? extends Asset> value) {
        this.underlyingAsset = value;
    }

    /**
     * Gets the value of the constituentWeight property.
     * 
     * @return
     *     possible object is
     *     {@link ConstituentWeight }
     *     
     */
    public ConstituentWeight getConstituentWeight() {
        return constituentWeight;
    }

    /**
     * Sets the value of the constituentWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstituentWeight }
     *     
     */
    public void setConstituentWeight(ConstituentWeight value) {
        this.constituentWeight = value;
    }

    /**
     * Gets the value of the dividendPayout property.
     * 
     * @return
     *     possible object is
     *     {@link DividendPayout }
     *     
     */
    public DividendPayout getDividendPayout() {
        return dividendPayout;
    }

    /**
     * Sets the value of the dividendPayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendPayout }
     *     
     */
    public void setDividendPayout(DividendPayout value) {
        this.dividendPayout = value;
    }

    /**
     * Gets the value of the underlyerPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getUnderlyerPrice() {
        return underlyerPrice;
    }

    /**
     * Sets the value of the underlyerPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setUnderlyerPrice(Price value) {
        this.underlyerPrice = value;
    }

    /**
     * Gets the value of the underlyerNotional property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getUnderlyerNotional() {
        return underlyerNotional;
    }

    /**
     * Sets the value of the underlyerNotional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setUnderlyerNotional(Money value) {
        this.underlyerNotional = value;
    }

    /**
     * Gets the value of the underlyerSpread property.
     * 
     * @return
     *     possible object is
     *     {@link SpreadScheduleReference }
     *     
     */
    public SpreadScheduleReference getUnderlyerSpread() {
        return underlyerSpread;
    }

    /**
     * Sets the value of the underlyerSpread property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpreadScheduleReference }
     *     
     */
    public void setUnderlyerSpread(SpreadScheduleReference value) {
        this.underlyerSpread = value;
    }

    /**
     * Gets the value of the couponPayment property.
     * 
     * @return
     *     possible object is
     *     {@link PendingPayment }
     *     
     */
    public PendingPayment getCouponPayment() {
        return couponPayment;
    }

    /**
     * Sets the value of the couponPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PendingPayment }
     *     
     */
    public void setCouponPayment(PendingPayment value) {
        this.couponPayment = value;
    }

    /**
     * Gets the value of the underlyerFinancing property.
     * 
     * @return
     *     possible object is
     *     {@link UnderlyerInterestLeg }
     *     
     */
    public UnderlyerInterestLeg getUnderlyerFinancing() {
        return underlyerFinancing;
    }

    /**
     * Sets the value of the underlyerFinancing property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderlyerInterestLeg }
     *     
     */
    public void setUnderlyerFinancing(UnderlyerInterestLeg value) {
        this.underlyerFinancing = value;
    }

    /**
     * Gets the value of the underlyerLoanRate property.
     * 
     * @return
     *     possible object is
     *     {@link UnderlyerLoanRate }
     *     
     */
    public UnderlyerLoanRate getUnderlyerLoanRate() {
        return underlyerLoanRate;
    }

    /**
     * Sets the value of the underlyerLoanRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderlyerLoanRate }
     *     
     */
    public void setUnderlyerLoanRate(UnderlyerLoanRate value) {
        this.underlyerLoanRate = value;
    }

    /**
     * Gets the value of the underlyerCollateral property.
     * 
     * @return
     *     possible object is
     *     {@link Collateral }
     *     
     */
    public Collateral getUnderlyerCollateral() {
        return underlyerCollateral;
    }

    /**
     * Sets the value of the underlyerCollateral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Collateral }
     *     
     */
    public void setUnderlyerCollateral(Collateral value) {
        this.underlyerCollateral = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
