//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A Bond Option
 * 
 * <p>Java class for BondOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BondOption"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}OptionBaseExtended"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="strike" type="{http://www.fpml.org/FpML-5/confirmation}BondOptionStrike"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/confirmation}BondChoice.model"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BondOption", propOrder = {
    "strike",
    "bond",
    "convertibleBond"
})
public class BondOption
    extends OptionBaseExtended
{

    @XmlElement(required = true)
    protected BondOptionStrike strike;
    protected Bond bond;
    protected ConvertibleBond convertibleBond;

    /**
     * Gets the value of the strike property.
     * 
     * @return
     *     possible object is
     *     {@link BondOptionStrike }
     *     
     */
    public BondOptionStrike getStrike() {
        return strike;
    }

    /**
     * Sets the value of the strike property.
     * 
     * @param value
     *     allowed object is
     *     {@link BondOptionStrike }
     *     
     */
    public void setStrike(BondOptionStrike value) {
        this.strike = value;
    }

    /**
     * A bond instrument referenced by a contract
     * 
     * @return
     *     possible object is
     *     {@link Bond }
     *     
     */
    public Bond getBond() {
        return bond;
    }

    /**
     * Sets the value of the bond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bond }
     *     
     */
    public void setBond(Bond value) {
        this.bond = value;
    }

    /**
     * A convertible bond instrument referenced by a contract.
     * 
     * @return
     *     possible object is
     *     {@link ConvertibleBond }
     *     
     */
    public ConvertibleBond getConvertibleBond() {
        return convertibleBond;
    }

    /**
     * Sets the value of the convertibleBond property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConvertibleBond }
     *     
     */
    public void setConvertibleBond(ConvertibleBond value) {
        this.convertibleBond = value;
    }

}
