//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A type definining the parameters used in the calculation of fixed or floating calculation period amounts.
 * 
 * <p>Java class for Calculation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Calculation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="notionalSchedule" type="{http://www.fpml.org/FpML-5/confirmation}Notional"/&gt;
 *           &lt;element name="fxLinkedNotionalSchedule" type="{http://www.fpml.org/FpML-5/confirmation}FxLinkedNotionalSchedule"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="fixedRateSchedule" type="{http://www.fpml.org/FpML-5/confirmation}Schedule"/&gt;
 *             &lt;element name="futureValueNotional" type="{http://www.fpml.org/FpML-5/confirmation}FutureValueAmount" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element ref="{http://www.fpml.org/FpML-5/confirmation}rateCalculation"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="dayCountFraction" type="{http://www.fpml.org/FpML-5/confirmation}DayCountFraction"/&gt;
 *         &lt;element name="discounting" type="{http://www.fpml.org/FpML-5/confirmation}Discounting" minOccurs="0"/&gt;
 *         &lt;element name="compoundingMethod" type="{http://www.fpml.org/FpML-5/confirmation}CompoundingMethodEnum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Calculation", propOrder = {
    "notionalSchedule",
    "fxLinkedNotionalSchedule",
    "fixedRateSchedule",
    "futureValueNotional",
    "rateCalculation",
    "dayCountFraction",
    "discounting",
    "compoundingMethod"
})
public class Calculation {

    protected Notional notionalSchedule;
    protected FxLinkedNotionalSchedule fxLinkedNotionalSchedule;
    protected Schedule fixedRateSchedule;
    protected FutureValueAmount futureValueNotional;
    @XmlElementRef(name = "rateCalculation", namespace = "http://www.fpml.org/FpML-5/confirmation", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends Rate> rateCalculation;
    @XmlElement(required = true)
    protected DayCountFraction dayCountFraction;
    protected Discounting discounting;
    @XmlSchemaType(name = "token")
    protected CompoundingMethodEnum compoundingMethod;

    /**
     * Gets the value of the notionalSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link Notional }
     *     
     */
    public Notional getNotionalSchedule() {
        return notionalSchedule;
    }

    /**
     * Sets the value of the notionalSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notional }
     *     
     */
    public void setNotionalSchedule(Notional value) {
        this.notionalSchedule = value;
    }

    /**
     * Gets the value of the fxLinkedNotionalSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link FxLinkedNotionalSchedule }
     *     
     */
    public FxLinkedNotionalSchedule getFxLinkedNotionalSchedule() {
        return fxLinkedNotionalSchedule;
    }

    /**
     * Sets the value of the fxLinkedNotionalSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxLinkedNotionalSchedule }
     *     
     */
    public void setFxLinkedNotionalSchedule(FxLinkedNotionalSchedule value) {
        this.fxLinkedNotionalSchedule = value;
    }

    /**
     * Gets the value of the fixedRateSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule }
     *     
     */
    public Schedule getFixedRateSchedule() {
        return fixedRateSchedule;
    }

    /**
     * Sets the value of the fixedRateSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule }
     *     
     */
    public void setFixedRateSchedule(Schedule value) {
        this.fixedRateSchedule = value;
    }

    /**
     * Gets the value of the futureValueNotional property.
     * 
     * @return
     *     possible object is
     *     {@link FutureValueAmount }
     *     
     */
    public FutureValueAmount getFutureValueNotional() {
        return futureValueNotional;
    }

    /**
     * Sets the value of the futureValueNotional property.
     * 
     * @param value
     *     allowed object is
     *     {@link FutureValueAmount }
     *     
     */
    public void setFutureValueNotional(FutureValueAmount value) {
        this.futureValueNotional = value;
    }

    /**
     * This element is the head of a substitution group. It is substituted by the floatingRateCalculation element for standard Floating Rate legs, or the inflationRateCalculation element for inflation swaps.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FloatingRateCalculation }{@code >}
     *     {@link JAXBElement }{@code <}{@link InflationRateCalculation }{@code >}
     *     {@link JAXBElement }{@code <}{@link Rate }{@code >}
     *     
     */
    public JAXBElement<? extends Rate> getRateCalculation() {
        return rateCalculation;
    }

    /**
     * Sets the value of the rateCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FloatingRateCalculation }{@code >}
     *     {@link JAXBElement }{@code <}{@link InflationRateCalculation }{@code >}
     *     {@link JAXBElement }{@code <}{@link Rate }{@code >}
     *     
     */
    public void setRateCalculation(JAXBElement<? extends Rate> value) {
        this.rateCalculation = value;
    }

    /**
     * Gets the value of the dayCountFraction property.
     * 
     * @return
     *     possible object is
     *     {@link DayCountFraction }
     *     
     */
    public DayCountFraction getDayCountFraction() {
        return dayCountFraction;
    }

    /**
     * Sets the value of the dayCountFraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayCountFraction }
     *     
     */
    public void setDayCountFraction(DayCountFraction value) {
        this.dayCountFraction = value;
    }

    /**
     * Gets the value of the discounting property.
     * 
     * @return
     *     possible object is
     *     {@link Discounting }
     *     
     */
    public Discounting getDiscounting() {
        return discounting;
    }

    /**
     * Sets the value of the discounting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discounting }
     *     
     */
    public void setDiscounting(Discounting value) {
        this.discounting = value;
    }

    /**
     * Gets the value of the compoundingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CompoundingMethodEnum }
     *     
     */
    public CompoundingMethodEnum getCompoundingMethod() {
        return compoundingMethod;
    }

    /**
     * Sets the value of the compoundingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompoundingMethodEnum }
     *     
     */
    public void setCompoundingMethod(CompoundingMethodEnum value) {
        this.compoundingMethod = value;
    }

}
