//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A type defining the characteristics of the coal being traded in a physically settled gas transaction.
 * 
 * <p>Java class for CoalProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoalProduct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="type" type="{http://www.fpml.org/FpML-5/confirmation}CoalProductType"/&gt;
 *           &lt;element name="coalProductSpecifications" type="{http://www.fpml.org/FpML-5/confirmation}CoalProductSpecifications"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="source" type="{http://www.fpml.org/FpML-5/confirmation}CoalProductSource" maxOccurs="unbounded"/&gt;
 *         &lt;element name="sCoTASpecifications" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/confirmation}CommodityUSCoalProduct.model" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoalProduct", propOrder = {
    "type",
    "coalProductSpecifications",
    "source",
    "sCoTASpecifications",
    "btuQualityAdjustment",
    "so2QualityAdjustment"
})
public class CoalProduct {

    protected CoalProductType type;
    protected CoalProductSpecifications coalProductSpecifications;
    @XmlElement(required = true)
    protected List<CoalProductSource> source;
    protected Boolean sCoTASpecifications;
    protected CoalQualityAdjustments btuQualityAdjustment;
    protected CoalQualityAdjustments so2QualityAdjustment;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CoalProductType }
     *     
     */
    public CoalProductType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoalProductType }
     *     
     */
    public void setType(CoalProductType value) {
        this.type = value;
    }

    /**
     * Gets the value of the coalProductSpecifications property.
     * 
     * @return
     *     possible object is
     *     {@link CoalProductSpecifications }
     *     
     */
    public CoalProductSpecifications getCoalProductSpecifications() {
        return coalProductSpecifications;
    }

    /**
     * Sets the value of the coalProductSpecifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoalProductSpecifications }
     *     
     */
    public void setCoalProductSpecifications(CoalProductSpecifications value) {
        this.coalProductSpecifications = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoalProductSource }
     * 
     * 
     */
    public List<CoalProductSource> getSource() {
        if (source == null) {
            source = new ArrayList<CoalProductSource>();
        }
        return this.source;
    }

    /**
     * Gets the value of the sCoTASpecifications property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSCoTASpecifications() {
        return sCoTASpecifications;
    }

    /**
     * Sets the value of the sCoTASpecifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSCoTASpecifications(Boolean value) {
        this.sCoTASpecifications = value;
    }

    /**
     * Gets the value of the btuQualityAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link CoalQualityAdjustments }
     *     
     */
    public CoalQualityAdjustments getBtuQualityAdjustment() {
        return btuQualityAdjustment;
    }

    /**
     * Sets the value of the btuQualityAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoalQualityAdjustments }
     *     
     */
    public void setBtuQualityAdjustment(CoalQualityAdjustments value) {
        this.btuQualityAdjustment = value;
    }

    /**
     * Gets the value of the so2QualityAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link CoalQualityAdjustments }
     *     
     */
    public CoalQualityAdjustments getSo2QualityAdjustment() {
        return so2QualityAdjustment;
    }

    /**
     * Sets the value of the so2QualityAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoalQualityAdjustments }
     *     
     */
    public void setSo2QualityAdjustment(CoalQualityAdjustments value) {
        this.so2QualityAdjustment = value;
    }

}
