//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An event defining a future change in facility commitment.
 * 
 * <p>Java class for CommitmentAdjustment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommitmentAdjustment"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}FacilityEvent"&gt;
 *       &lt;sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="refusalAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *           &lt;element name="scheduled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *           &lt;element name="pik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="facilityCommitment" type="{http://www.fpml.org/FpML-5/confirmation}FacilityCommitment"/&gt;
 *           &lt;element name="adjustment" type="{http://www.fpml.org/FpML-5/confirmation}Adjustment"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="commitmentSchedule" type="{http://www.fpml.org/FpML-5/confirmation}CommitmentSchedule" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommitmentAdjustment", propOrder = {
    "refusalAllowed",
    "scheduled",
    "pik",
    "facilityCommitment",
    "adjustment",
    "commitmentSchedule"
})
public class CommitmentAdjustment
    extends FacilityEvent
{

    protected boolean refusalAllowed;
    protected boolean scheduled;
    protected boolean pik;
    @XmlElement(required = true)
    protected FacilityCommitment facilityCommitment;
    @XmlElement(required = true)
    protected Adjustment adjustment;
    protected CommitmentSchedule commitmentSchedule;

    /**
     * Gets the value of the refusalAllowed property.
     * 
     */
    public boolean isRefusalAllowed() {
        return refusalAllowed;
    }

    /**
     * Sets the value of the refusalAllowed property.
     * 
     */
    public void setRefusalAllowed(boolean value) {
        this.refusalAllowed = value;
    }

    /**
     * Gets the value of the scheduled property.
     * 
     */
    public boolean isScheduled() {
        return scheduled;
    }

    /**
     * Sets the value of the scheduled property.
     * 
     */
    public void setScheduled(boolean value) {
        this.scheduled = value;
    }

    /**
     * Gets the value of the pik property.
     * 
     */
    public boolean isPik() {
        return pik;
    }

    /**
     * Sets the value of the pik property.
     * 
     */
    public void setPik(boolean value) {
        this.pik = value;
    }

    /**
     * Gets the value of the facilityCommitment property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityCommitment }
     *     
     */
    public FacilityCommitment getFacilityCommitment() {
        return facilityCommitment;
    }

    /**
     * Sets the value of the facilityCommitment property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityCommitment }
     *     
     */
    public void setFacilityCommitment(FacilityCommitment value) {
        this.facilityCommitment = value;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * @return
     *     possible object is
     *     {@link Adjustment }
     *     
     */
    public Adjustment getAdjustment() {
        return adjustment;
    }

    /**
     * Sets the value of the adjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adjustment }
     *     
     */
    public void setAdjustment(Adjustment value) {
        this.adjustment = value;
    }

    /**
     * Gets the value of the commitmentSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link CommitmentSchedule }
     *     
     */
    public CommitmentSchedule getCommitmentSchedule() {
        return commitmentSchedule;
    }

    /**
     * Sets the value of the commitmentSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommitmentSchedule }
     *     
     */
    public void setCommitmentSchedule(CommitmentSchedule value) {
        this.commitmentSchedule = value;
    }

}
