//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommoditySpread complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommoditySpread"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}Money"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="spreadConversionFactor" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="spreadUnit" type="{http://www.fpml.org/FpML-5/confirmation}QuantityUnit" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommoditySpread", propOrder = {
    "spreadConversionFactor",
    "spreadUnit"
})
public class CommoditySpread
    extends Money
{

    protected BigDecimal spreadConversionFactor;
    protected QuantityUnit spreadUnit;

    /**
     * Gets the value of the spreadConversionFactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpreadConversionFactor() {
        return spreadConversionFactor;
    }

    /**
     * Sets the value of the spreadConversionFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpreadConversionFactor(BigDecimal value) {
        this.spreadConversionFactor = value;
    }

    /**
     * Gets the value of the spreadUnit property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityUnit }
     *     
     */
    public QuantityUnit getSpreadUnit() {
        return spreadUnit;
    }

    /**
     * Sets the value of the spreadUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityUnit }
     *     
     */
    public void setSpreadUnit(QuantityUnit value) {
        this.spreadUnit = value;
    }

}
