//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * ISDA 1993 or 2005 commodity market disruption elements.
 * 
 * <p>Java class for CommodityMarketDisruption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommodityMarketDisruption"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="marketDisruptionEvents" type="{http://www.fpml.org/FpML-5/confirmation}MarketDisruptionEventsEnum"/&gt;
 *             &lt;element name="additionalMarketDisruptionEvent" type="{http://www.fpml.org/FpML-5/confirmation}MarketDisruptionEvent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="marketDisruptionEvent" type="{http://www.fpml.org/FpML-5/confirmation}MarketDisruptionEvent" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="disruptionFallbacks" type="{http://www.fpml.org/FpML-5/confirmation}DisruptionFallbacksEnum"/&gt;
 *           &lt;element name="disruptionFallback" type="{http://www.fpml.org/FpML-5/confirmation}SequencedDisruptionFallback" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="fallbackReferencePrice" type="{http://www.fpml.org/FpML-5/confirmation}Underlyer" minOccurs="0"/&gt;
 *         &lt;element name="maximumNumberOfDaysOfDisruption" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="priceMaterialityPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="minimumFuturesContracts" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommodityMarketDisruption", propOrder = {
    "marketDisruptionEvents",
    "additionalMarketDisruptionEvent",
    "marketDisruptionEvent",
    "disruptionFallbacks",
    "disruptionFallback",
    "fallbackReferencePrice",
    "maximumNumberOfDaysOfDisruption",
    "priceMaterialityPercentage",
    "minimumFuturesContracts"
})
public class CommodityMarketDisruption {

    @XmlSchemaType(name = "token")
    protected MarketDisruptionEventsEnum marketDisruptionEvents;
    protected List<MarketDisruptionEvent> additionalMarketDisruptionEvent;
    protected List<MarketDisruptionEvent> marketDisruptionEvent;
    @XmlSchemaType(name = "token")
    protected DisruptionFallbacksEnum disruptionFallbacks;
    protected List<SequencedDisruptionFallback> disruptionFallback;
    protected Underlyer fallbackReferencePrice;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maximumNumberOfDaysOfDisruption;
    protected BigDecimal priceMaterialityPercentage;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minimumFuturesContracts;

    /**
     * Gets the value of the marketDisruptionEvents property.
     * 
     * @return
     *     possible object is
     *     {@link MarketDisruptionEventsEnum }
     *     
     */
    public MarketDisruptionEventsEnum getMarketDisruptionEvents() {
        return marketDisruptionEvents;
    }

    /**
     * Sets the value of the marketDisruptionEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketDisruptionEventsEnum }
     *     
     */
    public void setMarketDisruptionEvents(MarketDisruptionEventsEnum value) {
        this.marketDisruptionEvents = value;
    }

    /**
     * Gets the value of the additionalMarketDisruptionEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the additionalMarketDisruptionEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalMarketDisruptionEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarketDisruptionEvent }
     * 
     * 
     */
    public List<MarketDisruptionEvent> getAdditionalMarketDisruptionEvent() {
        if (additionalMarketDisruptionEvent == null) {
            additionalMarketDisruptionEvent = new ArrayList<MarketDisruptionEvent>();
        }
        return this.additionalMarketDisruptionEvent;
    }

    /**
     * Gets the value of the marketDisruptionEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the marketDisruptionEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketDisruptionEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarketDisruptionEvent }
     * 
     * 
     */
    public List<MarketDisruptionEvent> getMarketDisruptionEvent() {
        if (marketDisruptionEvent == null) {
            marketDisruptionEvent = new ArrayList<MarketDisruptionEvent>();
        }
        return this.marketDisruptionEvent;
    }

    /**
     * Gets the value of the disruptionFallbacks property.
     * 
     * @return
     *     possible object is
     *     {@link DisruptionFallbacksEnum }
     *     
     */
    public DisruptionFallbacksEnum getDisruptionFallbacks() {
        return disruptionFallbacks;
    }

    /**
     * Sets the value of the disruptionFallbacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisruptionFallbacksEnum }
     *     
     */
    public void setDisruptionFallbacks(DisruptionFallbacksEnum value) {
        this.disruptionFallbacks = value;
    }

    /**
     * Gets the value of the disruptionFallback property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the disruptionFallback property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisruptionFallback().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SequencedDisruptionFallback }
     * 
     * 
     */
    public List<SequencedDisruptionFallback> getDisruptionFallback() {
        if (disruptionFallback == null) {
            disruptionFallback = new ArrayList<SequencedDisruptionFallback>();
        }
        return this.disruptionFallback;
    }

    /**
     * Gets the value of the fallbackReferencePrice property.
     * 
     * @return
     *     possible object is
     *     {@link Underlyer }
     *     
     */
    public Underlyer getFallbackReferencePrice() {
        return fallbackReferencePrice;
    }

    /**
     * Sets the value of the fallbackReferencePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Underlyer }
     *     
     */
    public void setFallbackReferencePrice(Underlyer value) {
        this.fallbackReferencePrice = value;
    }

    /**
     * Gets the value of the maximumNumberOfDaysOfDisruption property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaximumNumberOfDaysOfDisruption() {
        return maximumNumberOfDaysOfDisruption;
    }

    /**
     * Sets the value of the maximumNumberOfDaysOfDisruption property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaximumNumberOfDaysOfDisruption(BigInteger value) {
        this.maximumNumberOfDaysOfDisruption = value;
    }

    /**
     * Gets the value of the priceMaterialityPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceMaterialityPercentage() {
        return priceMaterialityPercentage;
    }

    /**
     * Sets the value of the priceMaterialityPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceMaterialityPercentage(BigDecimal value) {
        this.priceMaterialityPercentage = value;
    }

    /**
     * Gets the value of the minimumFuturesContracts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinimumFuturesContracts() {
        return minimumFuturesContracts;
    }

    /**
     * Sets the value of the minimumFuturesContracts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinimumFuturesContracts(BigInteger value) {
        this.minimumFuturesContracts = value;
    }

}
