//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A type defining a compounding rate. The compounding interest can either point back to the floating rate calculation of interest calculation node on the Interest Leg, or be defined specifically.
 * 
 * <p>Java class for CompoundingRate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompoundingRate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="interestLegRate" type="{http://www.fpml.org/FpML-5/confirmation}FloatingRateCalculationReference"/&gt;
 *         &lt;element name="specificRate" type="{http://www.fpml.org/FpML-5/confirmation}InterestAccrualsMethod"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompoundingRate", propOrder = {
    "interestLegRate",
    "specificRate"
})
public class CompoundingRate {

    protected FloatingRateCalculationReference interestLegRate;
    protected InterestAccrualsMethod specificRate;

    /**
     * Gets the value of the interestLegRate property.
     * 
     * @return
     *     possible object is
     *     {@link FloatingRateCalculationReference }
     *     
     */
    public FloatingRateCalculationReference getInterestLegRate() {
        return interestLegRate;
    }

    /**
     * Sets the value of the interestLegRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FloatingRateCalculationReference }
     *     
     */
    public void setInterestLegRate(FloatingRateCalculationReference value) {
        this.interestLegRate = value;
    }

    /**
     * Gets the value of the specificRate property.
     * 
     * @return
     *     possible object is
     *     {@link InterestAccrualsMethod }
     *     
     */
    public InterestAccrualsMethod getSpecificRate() {
        return specificRate;
    }

    /**
     * Sets the value of the specificRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestAccrualsMethod }
     *     
     */
    public void setSpecificRate(InterestAccrualsMethod value) {
        this.specificRate = value;
    }

}
