//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A type describing the dividend payout ratio associated with an equity underlyer. In certain cases the actual ratio is not known on trade inception, and only general conditions are then specified.
 * 
 * <p>Java class for DividendPayout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DividendPayout"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="dividendPayoutRatio" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *             &lt;element name="dividendPayoutRatioCash" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *             &lt;element name="dividendPayoutRatioNonCash" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="dividendPayoutConditions" type="{http://www.fpml.org/FpML-5/confirmation}String"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="dividendPayment" type="{http://www.fpml.org/FpML-5/confirmation}PendingPayment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DividendPayout", propOrder = {
    "dividendPayoutRatio",
    "dividendPayoutRatioCash",
    "dividendPayoutRatioNonCash",
    "dividendPayoutConditions",
    "dividendPayment"
})
public class DividendPayout {

    protected BigDecimal dividendPayoutRatio;
    protected BigDecimal dividendPayoutRatioCash;
    protected BigDecimal dividendPayoutRatioNonCash;
    protected String dividendPayoutConditions;
    protected List<PendingPayment> dividendPayment;

    /**
     * Gets the value of the dividendPayoutRatio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDividendPayoutRatio() {
        return dividendPayoutRatio;
    }

    /**
     * Sets the value of the dividendPayoutRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDividendPayoutRatio(BigDecimal value) {
        this.dividendPayoutRatio = value;
    }

    /**
     * Gets the value of the dividendPayoutRatioCash property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDividendPayoutRatioCash() {
        return dividendPayoutRatioCash;
    }

    /**
     * Sets the value of the dividendPayoutRatioCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDividendPayoutRatioCash(BigDecimal value) {
        this.dividendPayoutRatioCash = value;
    }

    /**
     * Gets the value of the dividendPayoutRatioNonCash property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDividendPayoutRatioNonCash() {
        return dividendPayoutRatioNonCash;
    }

    /**
     * Sets the value of the dividendPayoutRatioNonCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDividendPayoutRatioNonCash(BigDecimal value) {
        this.dividendPayoutRatioNonCash = value;
    }

    /**
     * Gets the value of the dividendPayoutConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDividendPayoutConditions() {
        return dividendPayoutConditions;
    }

    /**
     * Sets the value of the dividendPayoutConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDividendPayoutConditions(String value) {
        this.dividendPayoutConditions = value;
    }

    /**
     * Gets the value of the dividendPayment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the dividendPayment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDividendPayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PendingPayment }
     * 
     * 
     */
    public List<PendingPayment> getDividendPayment() {
        if (dividendPayment == null) {
            dividendPayment = new ArrayList<PendingPayment>();
        }
        return this.dividendPayment;
    }

}
