//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The abstract base type from which all FpML compliant messages and documents must be derived.
 * 
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attGroup ref="{http://www.fpml.org/FpML-5/confirmation}VersionAttributes.atts"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document")
@XmlSeeAlso({
    DataDocument.class,
    Message.class
})
public abstract class Document {

    @XmlAttribute(name = "fpmlVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fpmlVersion;
    @XmlAttribute(name = "expectedBuild")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger expectedBuild;
    @XmlAttribute(name = "actualBuild")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger actualBuild;

    /**
     * Gets the value of the fpmlVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpmlVersion() {
        return fpmlVersion;
    }

    /**
     * Sets the value of the fpmlVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpmlVersion(String value) {
        this.fpmlVersion = value;
    }

    /**
     * Gets the value of the expectedBuild property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpectedBuild() {
        return expectedBuild;
    }

    /**
     * Sets the value of the expectedBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpectedBuild(BigInteger value) {
        this.expectedBuild = value;
    }

    /**
     * Gets the value of the actualBuild property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActualBuild() {
        if (actualBuild == null) {
            return new BigInteger("7");
        } else {
            return actualBuild;
        }
    }

    /**
     * Sets the value of the actualBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setActualBuild(BigInteger value) {
        this.actualBuild = value;
    }

}
