//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The quantity of gas to be delivered.
 * 
 * <p>Java class for ElectricityPhysicalQuantity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElectricityPhysicalQuantity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}CommodityPhysicalQuantityBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="physicalQuantity" type="{http://www.fpml.org/FpML-5/confirmation}ElectricityPhysicalDeliveryQuantity" maxOccurs="unbounded"/&gt;
 *           &lt;element name="physicalQuantitySchedule" type="{http://www.fpml.org/FpML-5/confirmation}ElectricityPhysicalDeliveryQuantitySchedule" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="totalPhysicalQuantity" type="{http://www.fpml.org/FpML-5/confirmation}UnitQuantity" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElectricityPhysicalQuantity", propOrder = {
    "physicalQuantity",
    "physicalQuantitySchedule",
    "totalPhysicalQuantity"
})
public class ElectricityPhysicalQuantity
    extends CommodityPhysicalQuantityBase
{

    protected List<ElectricityPhysicalDeliveryQuantity> physicalQuantity;
    protected List<ElectricityPhysicalDeliveryQuantitySchedule> physicalQuantitySchedule;
    protected UnitQuantity totalPhysicalQuantity;

    /**
     * Gets the value of the physicalQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the physicalQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElectricityPhysicalDeliveryQuantity }
     * 
     * 
     */
    public List<ElectricityPhysicalDeliveryQuantity> getPhysicalQuantity() {
        if (physicalQuantity == null) {
            physicalQuantity = new ArrayList<ElectricityPhysicalDeliveryQuantity>();
        }
        return this.physicalQuantity;
    }

    /**
     * Gets the value of the physicalQuantitySchedule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the physicalQuantitySchedule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalQuantitySchedule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElectricityPhysicalDeliveryQuantitySchedule }
     * 
     * 
     */
    public List<ElectricityPhysicalDeliveryQuantitySchedule> getPhysicalQuantitySchedule() {
        if (physicalQuantitySchedule == null) {
            physicalQuantitySchedule = new ArrayList<ElectricityPhysicalDeliveryQuantitySchedule>();
        }
        return this.physicalQuantitySchedule;
    }

    /**
     * Gets the value of the totalPhysicalQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link UnitQuantity }
     *     
     */
    public UnitQuantity getTotalPhysicalQuantity() {
        return totalPhysicalQuantity;
    }

    /**
     * Sets the value of the totalPhysicalQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitQuantity }
     *     
     */
    public void setTotalPhysicalQuantity(UnitQuantity value) {
        this.totalPhysicalQuantity = value;
    }

}
