//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A type for defining equity options.
 * 
 * <p>Java class for EquityOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquityOption"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}EquityDerivativeLongFormBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="strike" type="{http://www.fpml.org/FpML-5/confirmation}EquityStrike" minOccurs="0"/&gt;
 *         &lt;element name="spotPrice" type="{http://www.fpml.org/FpML-5/confirmation}NonNegativeDecimal" minOccurs="0"/&gt;
 *         &lt;element name="numberOfOptions" type="{http://www.fpml.org/FpML-5/confirmation}NonNegativeDecimal" minOccurs="0"/&gt;
 *         &lt;element name="optionEntitlement" type="{http://www.fpml.org/FpML-5/confirmation}PositiveDecimal"/&gt;
 *         &lt;element name="equityPremium" type="{http://www.fpml.org/FpML-5/confirmation}EquityPremium"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquityOption", propOrder = {
    "strike",
    "spotPrice",
    "numberOfOptions",
    "optionEntitlement",
    "equityPremium"
})
public class EquityOption
    extends EquityDerivativeLongFormBase
{

    protected EquityStrike strike;
    protected BigDecimal spotPrice;
    protected BigDecimal numberOfOptions;
    @XmlElement(required = true)
    protected BigDecimal optionEntitlement;
    @XmlElement(required = true)
    protected EquityPremium equityPremium;

    /**
     * Gets the value of the strike property.
     * 
     * @return
     *     possible object is
     *     {@link EquityStrike }
     *     
     */
    public EquityStrike getStrike() {
        return strike;
    }

    /**
     * Sets the value of the strike property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquityStrike }
     *     
     */
    public void setStrike(EquityStrike value) {
        this.strike = value;
    }

    /**
     * Gets the value of the spotPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpotPrice() {
        return spotPrice;
    }

    /**
     * Sets the value of the spotPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpotPrice(BigDecimal value) {
        this.spotPrice = value;
    }

    /**
     * Gets the value of the numberOfOptions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumberOfOptions() {
        return numberOfOptions;
    }

    /**
     * Sets the value of the numberOfOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumberOfOptions(BigDecimal value) {
        this.numberOfOptions = value;
    }

    /**
     * Gets the value of the optionEntitlement property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOptionEntitlement() {
        return optionEntitlement;
    }

    /**
     * Sets the value of the optionEntitlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOptionEntitlement(BigDecimal value) {
        this.optionEntitlement = value;
    }

    /**
     * Gets the value of the equityPremium property.
     * 
     * @return
     *     possible object is
     *     {@link EquityPremium }
     *     
     */
    public EquityPremium getEquityPremium() {
        return equityPremium;
    }

    /**
     * Sets the value of the equityPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquityPremium }
     *     
     */
    public void setEquityPremium(EquityPremium value) {
        this.equityPremium = value;
    }

}
