//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An FX Range Accrual product. A strip of Digital Options product The product defines a list of fixing (or observation) dates. There are m total fixings. On the relevant Settlement Date, the Option Seller shall pay to the Option Buyer an amount, in the Settlement Currency, calculated according to the following formula: Accrual Currency and Notional Amount x (the total number of Accrual Days / Total Number of Calendar Days in the Accrual Period). Payout can be cash.
 * 
 * <p>Java class for FxRangeAccrual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FxRangeAccrual"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}Product"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/confirmation}PayerReceiver.model"/&gt;
 *         &lt;element name="notionalAmount" type="{http://www.fpml.org/FpML-5/confirmation}NonNegativeAmountSchedule"/&gt;
 *         &lt;element name="accrual" type="{http://www.fpml.org/FpML-5/confirmation}FxAccrual"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/confirmation}FxExpiryDateOrSchedule.model"/&gt;
 *         &lt;group ref="{http://www.fpml.org/FpML-5/confirmation}FxSettlementDateOrSchedule.model"/&gt;
 *         &lt;element name="barrier" type="{http://www.fpml.org/FpML-5/confirmation}FxAccrualBarrier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="premium" type="{http://www.fpml.org/FpML-5/confirmation}FxOptionPremium" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FxRangeAccrual", propOrder = {
    "payerPartyReference",
    "payerAccountReference",
    "receiverPartyReference",
    "receiverAccountReference",
    "notionalAmount",
    "accrual",
    "expiryDate",
    "expirySchedule",
    "settlementDate",
    "settlementSchedule",
    "barrier",
    "premium"
})
public class FxRangeAccrual
    extends Product
{

    @XmlElement(required = true)
    protected PartyReference payerPartyReference;
    protected AccountReference payerAccountReference;
    @XmlElement(required = true)
    protected PartyReference receiverPartyReference;
    protected AccountReference receiverAccountReference;
    @XmlElement(required = true)
    protected NonNegativeAmountSchedule notionalAmount;
    @XmlElement(required = true)
    protected FxAccrual accrual;
    protected FxExpiryDate expiryDate;
    protected FxExpirySchedule expirySchedule;
    protected FxAdjustedDateAndDateAdjustments settlementDate;
    protected FxSettlementSchedule settlementSchedule;
    protected List<FxAccrualBarrier> barrier;
    protected List<FxOptionPremium> premium;

    /**
     * Gets the value of the payerPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getPayerPartyReference() {
        return payerPartyReference;
    }

    /**
     * Sets the value of the payerPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setPayerPartyReference(PartyReference value) {
        this.payerPartyReference = value;
    }

    /**
     * Gets the value of the payerAccountReference property.
     * 
     * @return
     *     possible object is
     *     {@link AccountReference }
     *     
     */
    public AccountReference getPayerAccountReference() {
        return payerAccountReference;
    }

    /**
     * Sets the value of the payerAccountReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountReference }
     *     
     */
    public void setPayerAccountReference(AccountReference value) {
        this.payerAccountReference = value;
    }

    /**
     * Gets the value of the receiverPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getReceiverPartyReference() {
        return receiverPartyReference;
    }

    /**
     * Sets the value of the receiverPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setReceiverPartyReference(PartyReference value) {
        this.receiverPartyReference = value;
    }

    /**
     * Gets the value of the receiverAccountReference property.
     * 
     * @return
     *     possible object is
     *     {@link AccountReference }
     *     
     */
    public AccountReference getReceiverAccountReference() {
        return receiverAccountReference;
    }

    /**
     * Sets the value of the receiverAccountReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountReference }
     *     
     */
    public void setReceiverAccountReference(AccountReference value) {
        this.receiverAccountReference = value;
    }

    /**
     * Gets the value of the notionalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeAmountSchedule }
     *     
     */
    public NonNegativeAmountSchedule getNotionalAmount() {
        return notionalAmount;
    }

    /**
     * Sets the value of the notionalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeAmountSchedule }
     *     
     */
    public void setNotionalAmount(NonNegativeAmountSchedule value) {
        this.notionalAmount = value;
    }

    /**
     * Gets the value of the accrual property.
     * 
     * @return
     *     possible object is
     *     {@link FxAccrual }
     *     
     */
    public FxAccrual getAccrual() {
        return accrual;
    }

    /**
     * Sets the value of the accrual property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxAccrual }
     *     
     */
    public void setAccrual(FxAccrual value) {
        this.accrual = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link FxExpiryDate }
     *     
     */
    public FxExpiryDate getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxExpiryDate }
     *     
     */
    public void setExpiryDate(FxExpiryDate value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the expirySchedule property.
     * 
     * @return
     *     possible object is
     *     {@link FxExpirySchedule }
     *     
     */
    public FxExpirySchedule getExpirySchedule() {
        return expirySchedule;
    }

    /**
     * Sets the value of the expirySchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxExpirySchedule }
     *     
     */
    public void setExpirySchedule(FxExpirySchedule value) {
        this.expirySchedule = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link FxAdjustedDateAndDateAdjustments }
     *     
     */
    public FxAdjustedDateAndDateAdjustments getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxAdjustedDateAndDateAdjustments }
     *     
     */
    public void setSettlementDate(FxAdjustedDateAndDateAdjustments value) {
        this.settlementDate = value;
    }

    /**
     * Gets the value of the settlementSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link FxSettlementSchedule }
     *     
     */
    public FxSettlementSchedule getSettlementSchedule() {
        return settlementSchedule;
    }

    /**
     * Sets the value of the settlementSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxSettlementSchedule }
     *     
     */
    public void setSettlementSchedule(FxSettlementSchedule value) {
        this.settlementSchedule = value;
    }

    /**
     * Gets the value of the barrier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the barrier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBarrier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FxAccrualBarrier }
     * 
     * 
     */
    public List<FxAccrualBarrier> getBarrier() {
        if (barrier == null) {
            barrier = new ArrayList<FxAccrualBarrier>();
        }
        return this.barrier;
    }

    /**
     * Gets the value of the premium property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the premium property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPremium().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FxOptionPremium }
     * 
     * 
     */
    public List<FxOptionPremium> getPremium() {
        if (premium == null) {
            premium = new ArrayList<FxOptionPremium>();
        }
        return this.premium;
    }

}
