//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenericCommodityDeliveryPeriod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericCommodityDeliveryPeriod"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="applicableDay" type="{http://www.fpml.org/FpML-5/confirmation}DayOfWeekExtEnum" maxOccurs="7"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="startTime" type="{http://www.fpml.org/FpML-5/confirmation}OffsetPrevailingTime"/&gt;
 *           &lt;element name="endTime" type="{http://www.fpml.org/FpML-5/confirmation}OffsetPrevailingTime"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericCommodityDeliveryPeriod", propOrder = {
    "applicableDay",
    "startTime",
    "endTime"
})
public class GenericCommodityDeliveryPeriod {

    @XmlElement(required = true)
    protected List<String> applicableDay;
    protected OffsetPrevailingTime startTime;
    protected OffsetPrevailingTime endTime;

    /**
     * Gets the value of the applicableDay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the applicableDay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicableDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getApplicableDay() {
        if (applicableDay == null) {
            applicableDay = new ArrayList<String>();
        }
        return this.applicableDay;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link OffsetPrevailingTime }
     *     
     */
    public OffsetPrevailingTime getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffsetPrevailingTime }
     *     
     */
    public void setStartTime(OffsetPrevailingTime value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link OffsetPrevailingTime }
     *     
     */
    public OffsetPrevailingTime getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffsetPrevailingTime }
     *     
     */
    public void setEndTime(OffsetPrevailingTime value) {
        this.endTime = value;
    }

}
