//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A payment component owed from one party to the other for the cash flow date. This payment component should by of only a single type, e.g. a fee or a cashflow from a cashflow stream.
 * 
 * <p>Java class for GrossCashflow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GrossCashflow"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="cashflowId" type="{http://www.fpml.org/FpML-5/confirmation}CashflowId"/&gt;
 *           &lt;element name="partyTradeIdentifierReference" type="{http://www.fpml.org/FpML-5/confirmation}PartyTradeIdentifierReference" minOccurs="0"/&gt;
 *           &lt;group ref="{http://www.fpml.org/FpML-5/confirmation}PayerReceiver.model"/&gt;
 *           &lt;element name="cashflowAmount" type="{http://www.fpml.org/FpML-5/confirmation}Money"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="cashflowType" type="{http://www.fpml.org/FpML-5/confirmation}CashflowType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GrossCashflow", propOrder = {
    "cashflowId",
    "partyTradeIdentifierReference",
    "payerPartyReference",
    "payerAccountReference",
    "receiverPartyReference",
    "receiverAccountReference",
    "cashflowAmount",
    "cashflowType"
})
public class GrossCashflow {

    protected CashflowId cashflowId;
    protected PartyTradeIdentifierReference partyTradeIdentifierReference;
    protected PartyReference payerPartyReference;
    protected AccountReference payerAccountReference;
    protected PartyReference receiverPartyReference;
    protected AccountReference receiverAccountReference;
    protected Money cashflowAmount;
    protected CashflowType cashflowType;

    /**
     * Gets the value of the cashflowId property.
     * 
     * @return
     *     possible object is
     *     {@link CashflowId }
     *     
     */
    public CashflowId getCashflowId() {
        return cashflowId;
    }

    /**
     * Sets the value of the cashflowId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashflowId }
     *     
     */
    public void setCashflowId(CashflowId value) {
        this.cashflowId = value;
    }

    /**
     * Gets the value of the partyTradeIdentifierReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyTradeIdentifierReference }
     *     
     */
    public PartyTradeIdentifierReference getPartyTradeIdentifierReference() {
        return partyTradeIdentifierReference;
    }

    /**
     * Sets the value of the partyTradeIdentifierReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyTradeIdentifierReference }
     *     
     */
    public void setPartyTradeIdentifierReference(PartyTradeIdentifierReference value) {
        this.partyTradeIdentifierReference = value;
    }

    /**
     * Gets the value of the payerPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getPayerPartyReference() {
        return payerPartyReference;
    }

    /**
     * Sets the value of the payerPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setPayerPartyReference(PartyReference value) {
        this.payerPartyReference = value;
    }

    /**
     * Gets the value of the payerAccountReference property.
     * 
     * @return
     *     possible object is
     *     {@link AccountReference }
     *     
     */
    public AccountReference getPayerAccountReference() {
        return payerAccountReference;
    }

    /**
     * Sets the value of the payerAccountReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountReference }
     *     
     */
    public void setPayerAccountReference(AccountReference value) {
        this.payerAccountReference = value;
    }

    /**
     * Gets the value of the receiverPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getReceiverPartyReference() {
        return receiverPartyReference;
    }

    /**
     * Sets the value of the receiverPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setReceiverPartyReference(PartyReference value) {
        this.receiverPartyReference = value;
    }

    /**
     * Gets the value of the receiverAccountReference property.
     * 
     * @return
     *     possible object is
     *     {@link AccountReference }
     *     
     */
    public AccountReference getReceiverAccountReference() {
        return receiverAccountReference;
    }

    /**
     * Sets the value of the receiverAccountReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountReference }
     *     
     */
    public void setReceiverAccountReference(AccountReference value) {
        this.receiverAccountReference = value;
    }

    /**
     * Gets the value of the cashflowAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getCashflowAmount() {
        return cashflowAmount;
    }

    /**
     * Sets the value of the cashflowAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setCashflowAmount(Money value) {
        this.cashflowAmount = value;
    }

    /**
     * Gets the value of the cashflowType property.
     * 
     * @return
     *     possible object is
     *     {@link CashflowType }
     *     
     */
    public CashflowType getCashflowType() {
        return cashflowType;
    }

    /**
     * Sets the value of the cashflowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashflowType }
     *     
     */
    public void setCashflowType(CashflowType value) {
        this.cashflowType = value;
    }

}
