//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterpolationPeriodEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="InterpolationPeriodEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Initial"/&gt;
 *     &lt;enumeration value="InitialAndFinal"/&gt;
 *     &lt;enumeration value="Final"/&gt;
 *     &lt;enumeration value="AnyPeriod"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "InterpolationPeriodEnum")
@XmlEnum
public enum InterpolationPeriodEnum {


    /**
     * Interpolation is applicable to the initial period only.
     * 
     */
    @XmlEnumValue("Initial")
    INITIAL("Initial"),

    /**
     * Interpolation is applicable to the initial and final periods only.
     * 
     */
    @XmlEnumValue("InitialAndFinal")
    INITIAL_AND_FINAL("InitialAndFinal"),

    /**
     * Interpolation is applicable to the final period only.
     * 
     */
    @XmlEnumValue("Final")
    FINAL("Final"),

    /**
     * Interpolation is applicable to any non-standard period.
     * 
     */
    @XmlEnumValue("AnyPeriod")
    ANY_PERIOD("AnyPeriod");
    private final String value;

    InterpolationPeriodEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterpolationPeriodEnum fromValue(String v) {
        for (InterpolationPeriodEnum c: InterpolationPeriodEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
