//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObligationCategoryEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ObligationCategoryEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Payment"/&gt;
 *     &lt;enumeration value="BorrowedMoney"/&gt;
 *     &lt;enumeration value="ReferenceObligationsOnly"/&gt;
 *     &lt;enumeration value="Bond"/&gt;
 *     &lt;enumeration value="Loan"/&gt;
 *     &lt;enumeration value="BondOrLoan"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ObligationCategoryEnum")
@XmlEnum
public enum ObligationCategoryEnum {


    /**
     * ISDA term "Payment".
     * 
     */
    @XmlEnumValue("Payment")
    PAYMENT("Payment"),

    /**
     * ISDA term "Borrowed Money".
     * 
     */
    @XmlEnumValue("BorrowedMoney")
    BORROWED_MONEY("BorrowedMoney"),

    /**
     * ISDA term "Reference Obligations Only".
     * 
     */
    @XmlEnumValue("ReferenceObligationsOnly")
    REFERENCE_OBLIGATIONS_ONLY("ReferenceObligationsOnly"),

    /**
     * ISDA term "Bond".
     * 
     */
    @XmlEnumValue("Bond")
    BOND("Bond"),

    /**
     * ISDA term "Loan".
     * 
     */
    @XmlEnumValue("Loan")
    LOAN("Loan"),

    /**
     * ISDA term "Bond or Loan".
     * 
     */
    @XmlEnumValue("BondOrLoan")
    BOND_OR_LOAN("BondOrLoan");
    private final String value;

    ObligationCategoryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ObligationCategoryEnum fromValue(String v) {
        for (ObligationCategoryEnum c: ObligationCategoryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
