//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A collection of quoted assets.
 * 
 * <p>Java class for QuotedAssetSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuotedAssetSet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="instrumentSet" type="{http://www.fpml.org/FpML-5/confirmation}InstrumentSet" minOccurs="0"/&gt;
 *         &lt;element name="assetQuote" type="{http://www.fpml.org/FpML-5/confirmation}BasicAssetValuation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuotedAssetSet", propOrder = {
    "instrumentSet",
    "assetQuote"
})
@XmlSeeAlso({
    FxRateSet.class
})
public class QuotedAssetSet {

    protected InstrumentSet instrumentSet;
    protected List<BasicAssetValuation> assetQuote;

    /**
     * Gets the value of the instrumentSet property.
     * 
     * @return
     *     possible object is
     *     {@link InstrumentSet }
     *     
     */
    public InstrumentSet getInstrumentSet() {
        return instrumentSet;
    }

    /**
     * Sets the value of the instrumentSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstrumentSet }
     *     
     */
    public void setInstrumentSet(InstrumentSet value) {
        this.instrumentSet = value;
    }

    /**
     * Gets the value of the assetQuote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the assetQuote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetQuote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasicAssetValuation }
     * 
     * 
     */
    public List<BasicAssetValuation> getAssetQuote() {
        if (assetQuote == null) {
            assetQuote = new ArrayList<BasicAssetValuation>();
        }
        return this.assetQuote;
    }

}
