//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A type defining the parameters used to generate the reset dates schedule and associated fixing dates. The reset dates are determined relative to the calculation periods schedules dates.
 * 
 * <p>Java class for ResetDates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResetDates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="calculationPeriodDatesReference" type="{http://www.fpml.org/FpML-5/confirmation}CalculationPeriodDatesReference"/&gt;
 *         &lt;element name="resetRelativeTo" type="{http://www.fpml.org/FpML-5/confirmation}ResetRelativeToEnum" minOccurs="0"/&gt;
 *         &lt;element name="initialFixingDate" type="{http://www.fpml.org/FpML-5/confirmation}RelativeDateOffset" minOccurs="0"/&gt;
 *         &lt;element name="fixingDates" type="{http://www.fpml.org/FpML-5/confirmation}RelativeDateOffset"/&gt;
 *         &lt;element name="rateCutOffDaysOffset" type="{http://www.fpml.org/FpML-5/confirmation}Offset" minOccurs="0"/&gt;
 *         &lt;element name="resetFrequency" type="{http://www.fpml.org/FpML-5/confirmation}ResetFrequency"/&gt;
 *         &lt;element name="resetDatesAdjustments" type="{http://www.fpml.org/FpML-5/confirmation}BusinessDayAdjustments"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResetDates", propOrder = {
    "calculationPeriodDatesReference",
    "resetRelativeTo",
    "initialFixingDate",
    "fixingDates",
    "rateCutOffDaysOffset",
    "resetFrequency",
    "resetDatesAdjustments"
})
public class ResetDates {

    @XmlElement(required = true)
    protected CalculationPeriodDatesReference calculationPeriodDatesReference;
    @XmlSchemaType(name = "token")
    protected ResetRelativeToEnum resetRelativeTo;
    protected RelativeDateOffset initialFixingDate;
    @XmlElement(required = true)
    protected RelativeDateOffset fixingDates;
    protected Offset rateCutOffDaysOffset;
    @XmlElement(required = true)
    protected ResetFrequency resetFrequency;
    @XmlElement(required = true)
    protected BusinessDayAdjustments resetDatesAdjustments;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the calculationPeriodDatesReference property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationPeriodDatesReference }
     *     
     */
    public CalculationPeriodDatesReference getCalculationPeriodDatesReference() {
        return calculationPeriodDatesReference;
    }

    /**
     * Sets the value of the calculationPeriodDatesReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationPeriodDatesReference }
     *     
     */
    public void setCalculationPeriodDatesReference(CalculationPeriodDatesReference value) {
        this.calculationPeriodDatesReference = value;
    }

    /**
     * Gets the value of the resetRelativeTo property.
     * 
     * @return
     *     possible object is
     *     {@link ResetRelativeToEnum }
     *     
     */
    public ResetRelativeToEnum getResetRelativeTo() {
        return resetRelativeTo;
    }

    /**
     * Sets the value of the resetRelativeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResetRelativeToEnum }
     *     
     */
    public void setResetRelativeTo(ResetRelativeToEnum value) {
        this.resetRelativeTo = value;
    }

    /**
     * Gets the value of the initialFixingDate property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeDateOffset }
     *     
     */
    public RelativeDateOffset getInitialFixingDate() {
        return initialFixingDate;
    }

    /**
     * Sets the value of the initialFixingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeDateOffset }
     *     
     */
    public void setInitialFixingDate(RelativeDateOffset value) {
        this.initialFixingDate = value;
    }

    /**
     * Gets the value of the fixingDates property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeDateOffset }
     *     
     */
    public RelativeDateOffset getFixingDates() {
        return fixingDates;
    }

    /**
     * Sets the value of the fixingDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeDateOffset }
     *     
     */
    public void setFixingDates(RelativeDateOffset value) {
        this.fixingDates = value;
    }

    /**
     * Gets the value of the rateCutOffDaysOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Offset }
     *     
     */
    public Offset getRateCutOffDaysOffset() {
        return rateCutOffDaysOffset;
    }

    /**
     * Sets the value of the rateCutOffDaysOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offset }
     *     
     */
    public void setRateCutOffDaysOffset(Offset value) {
        this.rateCutOffDaysOffset = value;
    }

    /**
     * Gets the value of the resetFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link ResetFrequency }
     *     
     */
    public ResetFrequency getResetFrequency() {
        return resetFrequency;
    }

    /**
     * Sets the value of the resetFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResetFrequency }
     *     
     */
    public void setResetFrequency(ResetFrequency value) {
        this.resetFrequency = value;
    }

    /**
     * Gets the value of the resetDatesAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessDayAdjustments }
     *     
     */
    public BusinessDayAdjustments getResetDatesAdjustments() {
        return resetDatesAdjustments;
    }

    /**
     * Sets the value of the resetDatesAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessDayAdjustments }
     *     
     */
    public void setResetDatesAdjustments(BusinessDayAdjustments value) {
        this.resetDatesAdjustments = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
