//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StubPeriodTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="StubPeriodTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="ShortInitial"/&gt;
 *     &lt;enumeration value="ShortFinal"/&gt;
 *     &lt;enumeration value="LongInitial"/&gt;
 *     &lt;enumeration value="LongFinal"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StubPeriodTypeEnum")
@XmlEnum
public enum StubPeriodTypeEnum {


    /**
     * If there is a non regular period remaining it is left shorter than the streams calculation period frequency and placed at the start of the stream
     * 
     */
    @XmlEnumValue("ShortInitial")
    SHORT_INITIAL("ShortInitial"),

    /**
     * If there is a non regular period remaining it is left shorter than the streams calculation period frequency and placed at the end of the stream
     * 
     */
    @XmlEnumValue("ShortFinal")
    SHORT_FINAL("ShortFinal"),

    /**
     * If there is a non regular period remaining it is placed at the start of the stream and combined with the adjacent calculation period to give a long first calculation period
     * 
     */
    @XmlEnumValue("LongInitial")
    LONG_INITIAL("LongInitial"),

    /**
     * If there is a non regular period remaining it is placed at the end of the stream and combined with the adjacent calculation period to give a long last calculation period
     * 
     */
    @XmlEnumValue("LongFinal")
    LONG_FINAL("LongFinal");
    private final String value;

    StubPeriodTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StubPeriodTypeEnum fromValue(String v) {
        for (StubPeriodTypeEnum c: StubPeriodTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
