//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TimeTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Close"/&gt;
 *     &lt;enumeration value="Open"/&gt;
 *     &lt;enumeration value="OSP"/&gt;
 *     &lt;enumeration value="SpecificTime"/&gt;
 *     &lt;enumeration value="XETRA"/&gt;
 *     &lt;enumeration value="DerivativesClose"/&gt;
 *     &lt;enumeration value="AsSpecifiedInMasterConfirmation"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TimeTypeEnum")
@XmlEnum
public enum TimeTypeEnum {


    /**
     * The official closing time of the exchange on the valuation date.
     * 
     */
    @XmlEnumValue("Close")
    CLOSE("Close"),

    /**
     * The official opening time of the exchange on the valuation date.
     * 
     */
    @XmlEnumValue("Open")
    OPEN("Open"),

    /**
     * The time at which the official settlement price is determined.
     * 
     */
    OSP("OSP"),

    /**
     * The time specified in the element equityExpirationTime or valuationTime (as appropriate)
     * 
     */
    @XmlEnumValue("SpecificTime")
    SPECIFIC_TIME("SpecificTime"),

    /**
     * The time at which the official settlement price (following the auction by the exchange) is determined by the exchange.
     * 
     */
    XETRA("XETRA"),

    /**
     * The official closing time of the derivatives exchange on which a derivative contract is listed on that security underlyer.
     * 
     */
    @XmlEnumValue("DerivativesClose")
    DERIVATIVES_CLOSE("DerivativesClose"),

    /**
     * The time is determined as provided in the relevant Master Confirmation.
     * 
     */
    @XmlEnumValue("AsSpecifiedInMasterConfirmation")
    AS_SPECIFIED_IN_MASTER_CONFIRMATION("AsSpecifiedInMasterConfirmation");
    private final String value;

    TimeTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeTypeEnum fromValue(String v) {
        for (TimeTypeEnum c: TimeTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
