//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A type defining a trade identifier with a reference to the party that this trade is associated with.
 * 
 * <p>Java class for TradeIdentifierExtended complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeIdentifierExtended"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}TradeIdentifier"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="associatedPartyReference" type="{http://www.fpml.org/FpML-5/confirmation}PartyReference"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeIdentifierExtended", propOrder = {
    "associatedPartyReference"
})
public class TradeIdentifierExtended
    extends TradeIdentifier
{

    @XmlElement(required = true)
    protected PartyReference associatedPartyReference;

    /**
     * Gets the value of the associatedPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getAssociatedPartyReference() {
        return associatedPartyReference;
    }

    /**
     * Sets the value of the associatedPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setAssociatedPartyReference(PartyReference value) {
        this.associatedPartyReference = value;
    }

}
