//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TriggerTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TriggerTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="EqualOrLess"/&gt;
 *     &lt;enumeration value="EqualOrGreater"/&gt;
 *     &lt;enumeration value="Equal"/&gt;
 *     &lt;enumeration value="Less"/&gt;
 *     &lt;enumeration value="Greater"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TriggerTypeEnum")
@XmlEnum
public enum TriggerTypeEnum {


    /**
     * The underlyer price must be equal to or less than the Trigger level.
     * 
     */
    @XmlEnumValue("EqualOrLess")
    EQUAL_OR_LESS("EqualOrLess"),

    /**
     * The underlyer price must be equal to or greater than the Trigger level.
     * 
     */
    @XmlEnumValue("EqualOrGreater")
    EQUAL_OR_GREATER("EqualOrGreater"),

    /**
     * The underlyer price must be equal to the Trigger level.
     * 
     */
    @XmlEnumValue("Equal")
    EQUAL("Equal"),

    /**
     * The underlyer price must be less than the Trigger level.
     * 
     */
    @XmlEnumValue("Less")
    LESS("Less"),

    /**
     * The underlyer price must be greater than the Trigger level.
     * 
     */
    @XmlEnumValue("Greater")
    GREATER("Greater");
    private final String value;

    TriggerTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TriggerTypeEnum fromValue(String v) {
        for (TriggerTypeEnum c: TriggerTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
