//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Trigger point at which feature is effective.
 * 
 * <p>Java class for Trigger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trigger"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *           &lt;element name="levelPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *           &lt;choice&gt;
 *             &lt;element name="creditEvents" type="{http://www.fpml.org/FpML-5/confirmation}CreditEvents"/&gt;
 *             &lt;element name="creditEventsReference" type="{http://www.fpml.org/FpML-5/confirmation}CreditEventsReference"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="triggerType" type="{http://www.fpml.org/FpML-5/confirmation}TriggerTypeEnum" minOccurs="0"/&gt;
 *         &lt;element name="triggerTimeType" type="{http://www.fpml.org/FpML-5/confirmation}TriggerTimeTypeEnum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trigger", propOrder = {
    "level",
    "levelPercentage",
    "creditEvents",
    "creditEventsReference",
    "triggerType",
    "triggerTimeType"
})
public class Trigger {

    protected BigDecimal level;
    protected BigDecimal levelPercentage;
    protected CreditEvents creditEvents;
    protected CreditEventsReference creditEventsReference;
    @XmlSchemaType(name = "token")
    protected TriggerTypeEnum triggerType;
    @XmlSchemaType(name = "token")
    protected TriggerTimeTypeEnum triggerTimeType;

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLevel(BigDecimal value) {
        this.level = value;
    }

    /**
     * Gets the value of the levelPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLevelPercentage() {
        return levelPercentage;
    }

    /**
     * Sets the value of the levelPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLevelPercentage(BigDecimal value) {
        this.levelPercentage = value;
    }

    /**
     * Gets the value of the creditEvents property.
     * 
     * @return
     *     possible object is
     *     {@link CreditEvents }
     *     
     */
    public CreditEvents getCreditEvents() {
        return creditEvents;
    }

    /**
     * Sets the value of the creditEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditEvents }
     *     
     */
    public void setCreditEvents(CreditEvents value) {
        this.creditEvents = value;
    }

    /**
     * Gets the value of the creditEventsReference property.
     * 
     * @return
     *     possible object is
     *     {@link CreditEventsReference }
     *     
     */
    public CreditEventsReference getCreditEventsReference() {
        return creditEventsReference;
    }

    /**
     * Sets the value of the creditEventsReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditEventsReference }
     *     
     */
    public void setCreditEventsReference(CreditEventsReference value) {
        this.creditEventsReference = value;
    }

    /**
     * Gets the value of the triggerType property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerTypeEnum }
     *     
     */
    public TriggerTypeEnum getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the value of the triggerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerTypeEnum }
     *     
     */
    public void setTriggerType(TriggerTypeEnum value) {
        this.triggerType = value;
    }

    /**
     * Gets the value of the triggerTimeType property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerTimeTypeEnum }
     *     
     */
    public TriggerTimeTypeEnum getTriggerTimeType() {
        return triggerTimeType;
    }

    /**
     * Sets the value of the triggerTimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerTimeTypeEnum }
     *     
     */
    public void setTriggerTimeType(TriggerTimeTypeEnum value) {
        this.triggerTimeType = value;
    }

}
