//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.27 at 10:23:13 AM CEST 
//


package net.finmath.smartcontract.product.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A matrix of volatilities with dimension 0-3.
 * 
 * <p>Java class for VolatilityMatrix complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VolatilityMatrix"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}PricingStructureValuation"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataPoints" type="{http://www.fpml.org/FpML-5/confirmation}MultiDimensionalPricingData"/&gt;
 *         &lt;element name="adjustment" type="{http://www.fpml.org/FpML-5/confirmation}ParametricAdjustment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolatilityMatrix", propOrder = {
    "dataPoints",
    "adjustment"
})
public class VolatilityMatrix
    extends PricingStructureValuation
{

    @XmlElement(required = true)
    protected MultiDimensionalPricingData dataPoints;
    protected List<ParametricAdjustment> adjustment;

    /**
     * Gets the value of the dataPoints property.
     * 
     * @return
     *     possible object is
     *     {@link MultiDimensionalPricingData }
     *     
     */
    public MultiDimensionalPricingData getDataPoints() {
        return dataPoints;
    }

    /**
     * Sets the value of the dataPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiDimensionalPricingData }
     *     
     */
    public void setDataPoints(MultiDimensionalPricingData value) {
        this.dataPoints = value;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the adjustment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParametricAdjustment }
     * 
     * 
     */
    public List<ParametricAdjustment> getAdjustment() {
        if (adjustment == null) {
            adjustment = new ArrayList<ParametricAdjustment>();
        }
        return this.adjustment;
    }

}
